### ISSUE TITLE
Write a C++ program to convert infix expression into prefix expression.

### ISSUE THREAD

**Issue by poorab202** [poorab202/hacktoberfest-contribution-#1]
## Instructions:
- There is a C++ file named "InfixToPrefix.cpp" in repository. You need to add your code to that file.
- The code should be neat and understandable.
- Use comments wherever needed.
- Use OOP based programming fashion.

**Comment by Poorab-202** [comment]
Can I resolve this issue?

**Comment by poorab202** [comment]
> Can I resolve this issue?

I have assigned you this issue. Good luck!

**Comment by poorab202** [comment]
Thank you @Poorab-202 for solving this issue.
